# Generated by Django 5.0.2 on 2025-06-25 09:12

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_quantity_sold', models.PositiveIntegerField(default=0)),
                ('total_revenue_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3)),
                ('total_revenue', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('rank_by_orders', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_by_revenue', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_by_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'popular_products',
                'ordering': ['rank_by_revenue'],
            },
        ),
        migrations.CreateModel(
            name='SellerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3)),
                ('total_revenue', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_items_sold', models.PositiveIntegerField(default=0)),
                ('average_order_value_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3)),
                ('average_order_value', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('active_products', models.PositiveIntegerField(default=0)),
                ('out_of_stock_products', models.PositiveIntegerField(default=0)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('returning_customers', models.PositiveIntegerField(default=0)),
                ('new_reviews', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('store_views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product_views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seller_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SellerRevenueTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_target_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3)),
                ('monthly_target', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('current_month_revenue_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3)),
                ('current_month_revenue', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('quarterly_target_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3)),
                ('quarterly_target', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('current_quarter_revenue_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3)),
                ('current_quarter_revenue', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('annual_target_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3)),
                ('annual_target', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('current_year_revenue_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3)),
                ('current_year_revenue', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('best_month_revenue_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3)),
                ('best_month_revenue', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('best_month_date', models.DateField(blank=True, null=True)),
                ('best_day_revenue_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3)),
                ('best_day_revenue', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('best_day_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seller_revenue_tracker',
            },
        ),
    ]
