# Generated by Django 5.0.2 on 2025-06-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_products', to='users.sellerprofile'),
        ),
        migrations.AddField(
            model_name='selleranalytics',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='users.sellerprofile'),
        ),
        migrations.AddField(
            model_name='sellerrevenuetracker',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_tracker', to='users.sellerprofile'),
        ),
        migrations.AddIndex(
            model_name='popularproduct',
            index=models.Index(fields=['seller', 'period_start', 'period_end'], name='popular_pro_seller__019ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='popularproduct',
            index=models.Index(fields=['rank_by_revenue'], name='popular_pro_rank_by_fd0c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='popularproduct',
            index=models.Index(fields=['rank_by_orders'], name='popular_pro_rank_by_dbd43a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='popularproduct',
            unique_together={('seller', 'product', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='selleranalytics',
            index=models.Index(fields=['seller', 'date'], name='seller_anal_seller__3a5ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='selleranalytics',
            index=models.Index(fields=['date'], name='seller_anal_date_4b9b35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='selleranalytics',
            unique_together={('seller', 'date')},
        ),
    ]
