FROM node:18-alpine as builder

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies with the --only=production flag
RUN npm ci --only=production

# Copy project files
COPY . .

# Build the project
RUN npm run build

FROM nginx:alpine

# Copy the built project files to the Nginx HTML directory
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]