# Generated by Django 4.2.9 on 2025-06-11 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('id_number', models.CharField(help_text='NID/Passport/Birth Certificate Number', max_length=50)),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('General Clothing', 'General Clothing'), ('Thrifted Clothing', 'Thrifted Clothing'), ('Loose Fabric', 'Loose Fabric')], max_length=50)),
                ('founded_date', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('pickup_location', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='seller_logos/')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_method', models.CharField(choices=[('Bank', 'Bank'), ('bKash', 'bKash'), ('Nagad', 'Nagad')], max_length=20)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_seller_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='sellers_sel_status_5db1d7_idx'), models.Index(fields=['email'], name='sellers_sel_email_3e4053_idx'), models.Index(fields=['-created_at'], name='sellers_sel_created_0defb3_idx')],
            },
        ),
    ]
