# Generated by Django 5.0.2 on 2025-06-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seller_homepage_products'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sellerhomepageproduct',
            new_name='seller_home_seller__3ed534_idx',
            old_name='seller_homepage_products_seller_id_order_idx',
        ),
    ]
