# Generated by Django 4.2.9 on 2025-05-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('daily_active_users', models.PositiveIntegerField(default=0)),
                ('new_customer_registrations', models.PositiveIntegerField(default=0)),
                ('new_seller_registrations', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_cancellations', models.PositiveIntegerField(default=0)),
                ('products_added', models.PositiveIntegerField(default=0)),
                ('total_products_in_stock', models.PositiveIntegerField(default=0)),
                ('total_products_out_of_stock', models.PositiveIntegerField(default=0)),
                ('reviews_added', models.PositiveIntegerField(default=0)),
                ('flagged_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('cart_additions', models.PositiveIntegerField(default=0)),
                ('wishlist_additions', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cart_abandonment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('search_impressions', models.PositiveIntegerField(default=0)),
                ('search_clicks', models.PositiveIntegerField(default=0)),
                ('avg_search_position', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=200)),
                ('search_query', models.CharField(db_index=True, max_length=500)),
                ('results_count', models.PositiveIntegerField()),
                ('click_position', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=200)),
                ('activity_type', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('store_visit', 'Store Visit'), ('search', 'Search'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('checkout_start', 'Checkout Started'), ('order_complete', 'Order Completed')], db_index=True, max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
