# Generated by Django 5.0.2 on 2025-06-18 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0001_initial'),
        ('promos', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredpromo',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_promos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featuredpromo',
            name='target_user_interests',
            field=models.ManyToManyField(blank=True, to='products.category'),
        ),
        migrations.AddField(
            model_name='featuredpromo',
            name='promo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_placements', to='promos.promocode'),
        ),
        migrations.AddField(
            model_name='promoimpression',
            name='featured_promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='promos.featuredpromo'),
        ),
        migrations.AddField(
            model_name='promoimpression',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promorequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_promotion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promorequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_requests', to='users.sellerprofile'),
        ),
        migrations.AddField(
            model_name='promorequest',
            name='target_products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, to='products.category'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='applicable_sellers',
            field=models.ManyToManyField(blank=True, to='users.sellerprofile'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocode',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='promos.promotion'),
        ),
        migrations.AddField(
            model_name='promotionalcampaign',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_promos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionalcampaign',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='users.sellerprofile'),
        ),
        migrations.AddField(
            model_name='promotionalcampaign',
            name='target_categories',
            field=models.ManyToManyField(blank=True, to='products.category'),
        ),
        migrations.AddField(
            model_name='promotionalcampaign',
            name='target_products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
        migrations.AddField(
            model_name='promousage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to='orders.order'),
        ),
        migrations.AddField(
            model_name='promousage',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promos.promocode'),
        ),
        migrations.AddField(
            model_name='promousage',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promos.promotion'),
        ),
        migrations.AddField(
            model_name='promousage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerpromorequest',
            name='created_promo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_request', to='promos.promocode'),
        ),
        migrations.AddField(
            model_name='sellerpromorequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_seller_promo_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerpromorequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_promo_requests', to='users.sellerprofile'),
        ),
        migrations.AddIndex(
            model_name='featuredpromo',
            index=models.Index(fields=['placement', 'is_active', 'priority'], name='featured_pr_placeme_117244_idx'),
        ),
        migrations.AddIndex(
            model_name='featuredpromo',
            index=models.Index(fields=['promotion_start', 'promotion_end'], name='featured_pr_promoti_e31ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='promoimpression',
            index=models.Index(fields=['featured_promo', 'viewed_at'], name='promo_impre_feature_b11c44_idx'),
        ),
        migrations.AddIndex(
            model_name='promoimpression',
            index=models.Index(fields=['user'], name='promo_impre_user_id_b6a82d_idx'),
        ),
        migrations.AddIndex(
            model_name='promoimpression',
            index=models.Index(fields=['session_key'], name='promo_impre_session_4e8125_idx'),
        ),
        migrations.AddIndex(
            model_name='promorequest',
            index=models.Index(fields=['seller', 'status'], name='promo_reque_seller__4684f0_idx'),
        ),
        migrations.AddIndex(
            model_name='promorequest',
            index=models.Index(fields=['status'], name='promo_reque_status_4dd111_idx'),
        ),
        migrations.AddIndex(
            model_name='promorequest',
            index=models.Index(fields=['request_type'], name='promo_reque_request_33ca03_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['status'], name='promotions_status_239aab_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date', 'end_date'], name='promotions_start_d_e0aba6_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['promotion_type'], name='promotions_promoti_b9bf01_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_featured'], name='promotions_is_feat_49267f_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='promo_codes_code_5b1d05_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['promotion', 'is_active'], name='promo_codes_promoti_b5341b_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionalcampaign',
            index=models.Index(fields=['seller', 'status'], name='promotional_seller__d43c65_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionalcampaign',
            index=models.Index(fields=['status'], name='promotional_status_b1efda_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionalcampaign',
            index=models.Index(fields=['start_date', 'end_date'], name='promotional_start_d_1904f5_idx'),
        ),
        migrations.AddIndex(
            model_name='promousage',
            index=models.Index(fields=['user'], name='promo_usage_user_id_d5b96d_idx'),
        ),
        migrations.AddIndex(
            model_name='promousage',
            index=models.Index(fields=['promotion'], name='promo_usage_promoti_48cd0b_idx'),
        ),
        migrations.AddIndex(
            model_name='promousage',
            index=models.Index(fields=['used_at'], name='promo_usage_used_at_21e1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerpromorequest',
            index=models.Index(fields=['seller', 'status'], name='seller_prom_seller__da3d28_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerpromorequest',
            index=models.Index(fields=['status'], name='seller_prom_status_3b5f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerpromorequest',
            index=models.Index(fields=['created_at'], name='seller_prom_created_4289e3_idx'),
        ),
    ]
