# Generated by Django 5.0.2 on 2025-06-18 16:14

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('method_type', models.CharField(choices=[('standard', 'Standard Delivery'), ('express', 'Express Delivery'), ('overnight', 'Overnight Delivery'), ('pickup', 'Store Pickup'), ('free', 'Free Shipping')], max_length=20)),
                ('min_delivery_days', models.PositiveIntegerField(default=1)),
                ('max_delivery_days', models.PositiveIntegerField(default=7)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight in kg', max_digits=8, null=True)),
                ('max_dimensions', models.JSONField(blank=True, help_text='Max dimensions as {length, width, height}', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shipping_methods',
            },
        ),
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', max_length=5)),
                ('default_dimension_unit', models.CharField(choices=[('cm', 'Centimeters'), ('in', 'Inches')], default='cm', max_length=5)),
                ('default_package_weight', models.DecimalField(decimal_places=2, default=0.1, help_text='Default packaging weight', max_digits=5)),
                ('auto_calculate_dimensions', models.BooleanField(default=True)),
                ('global_free_shipping_threshold_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3, null=True)),
                ('global_free_shipping_threshold', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('free_shipping_message', models.CharField(blank=True, max_length=200)),
                ('processing_days', models.PositiveIntegerField(default=1, help_text='Days to process orders before shipping')),
                ('weekend_delivery', models.BooleanField(default=False)),
                ('holiday_delivery', models.BooleanField(default=False)),
                ('send_shipping_notifications', models.BooleanField(default=True)),
                ('send_delivery_notifications', models.BooleanField(default=True)),
                ('shipping_admin_email', models.EmailField(blank=True, max_length=254)),
                ('shipping_admin_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Settings',
                'verbose_name_plural': 'Shipping Settings',
                'db_table': 'shipping_settings',
            },
        ),
        migrations.CreateModel(
            name='ShippingCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('api_enabled', models.BooleanField(default=False)),
                ('api_credentials', models.JSONField(blank=True, default=dict)),
                ('tracking_url_template', models.CharField(blank=True, help_text='URL template with {tracking_number} placeholder', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shipping_carriers',
                'indexes': [models.Index(fields=['code'], name='shipping_ca_code_34a394_idx'), models.Index(fields=['is_active'], name='shipping_ca_is_acti_fdb7c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShippingLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('tracking_url', models.URLField(blank=True)),
                ('label_file', models.FileField(blank=True, upload_to='shipping/labels/')),
                ('label_format', models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG'), ('zpl', 'ZPL')], default='pdf', max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('dimensions', models.JSONField(blank=True, help_text='Dimensions as {length, width, height}', null=True)),
                ('declared_value_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3, null=True)),
                ('declared_value', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('printed', 'Printed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='created', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('is_insured', models.BooleanField(default=False)),
                ('insurance_amount_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3, null=True)),
                ('insurance_amount', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requires_signature', models.BooleanField(default=False)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_labels', to='shipping.shippingcarrier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_labels', to='orders.order')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.shippingmethod')),
            ],
            options={
                'db_table': 'shipping_labels',
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('countries', models.JSONField(default=list, help_text='List of countries in this zone')),
                ('states', models.JSONField(default=list, help_text='List of states/provinces')),
                ('cities', models.JSONField(default=list, help_text='List of cities')),
                ('postal_codes', models.JSONField(default=list, help_text='List of postal code patterns')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shipping_zones',
                'indexes': [models.Index(fields=['name'], name='shipping_zo_name_e1e80c_idx'), models.Index(fields=['is_active'], name='shipping_zo_is_acti_ae3818_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('flat', 'Flat Rate'), ('weight_based', 'Weight Based'), ('price_based', 'Price Based'), ('item_based', 'Per Item'), ('free', 'Free')], max_length=15)),
                ('base_rate_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3)),
                ('base_rate', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('rate_per_kg_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3, null=True)),
                ('rate_per_kg', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('free_shipping_threshold_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3, null=True)),
                ('free_shipping_threshold', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_tiers', models.JSONField(blank=True, default=list, help_text='Price tiers with rates')),
                ('min_order_value_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3, null=True)),
                ('min_order_value', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_order_value_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3, null=True)),
                ('max_order_value', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('handling_fee_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3)),
                ('handling_fee', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('fuel_surcharge_currency', djmoney.models.fields.CurrencyField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', editable=False, max_length=3)),
                ('fuel_surcharge', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingmethod')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='shipping.shippingzone')),
            ],
            options={
                'db_table': 'shipping_rates',
            },
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='zones',
            field=models.ManyToManyField(related_name='shipping_methods', through='shipping.ShippingRate', to='shipping.shippingzone'),
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('successful', 'Delivered Successfully'), ('failed', 'Delivery Failed'), ('rescheduled', 'Rescheduled'), ('returned', 'Returned to Sender')], max_length=15)),
                ('attempted_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('next_attempt_scheduled', models.DateTimeField(blank=True, null=True)),
                ('delivered_to', models.CharField(blank=True, max_length=200)),
                ('signature_required', models.BooleanField(default=False)),
                ('signature_obtained', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='shipping.shippinglabel')),
            ],
            options={
                'db_table': 'delivery_attempts',
                'ordering': ['attempt_number'],
                'indexes': [models.Index(fields=['label', 'attempted_at'], name='delivery_at_label_i_8be0e5_idx'), models.Index(fields=['status'], name='delivery_at_status_6dc4df_idx')],
                'unique_together': {('label', 'attempt_number')},
            },
        ),
        migrations.AddIndex(
            model_name='shippinglabel',
            index=models.Index(fields=['order'], name='shipping_la_order_i_188c43_idx'),
        ),
        migrations.AddIndex(
            model_name='shippinglabel',
            index=models.Index(fields=['tracking_number'], name='shipping_la_trackin_45c64b_idx'),
        ),
        migrations.AddIndex(
            model_name='shippinglabel',
            index=models.Index(fields=['status'], name='shipping_la_status_550533_idx'),
        ),
        migrations.AddIndex(
            model_name='shippinglabel',
            index=models.Index(fields=['created_at'], name='shipping_la_created_32c375_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingrate',
            index=models.Index(fields=['zone', 'method', 'is_active'], name='shipping_ra_zone_id_65c42f_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingrate',
            index=models.Index(fields=['calculation_type'], name='shipping_ra_calcula_c8fc1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingrate',
            unique_together={('zone', 'method')},
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['method_type'], name='shipping_me_method__f753df_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['is_active'], name='shipping_me_is_acti_ac7908_idx'),
        ),
    ]
