# Generated by Django 4.2.9 on 2025-05-29 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeteammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storefollow',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='storefollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storebankinginfo',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='storefollow',
            unique_together={('user', 'store')},
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['business_type', 'is_active'], name='stores_stor_busines_8e38fb_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['rating', 'verified'], name='stores_stor_rating_4ec3a5_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['-created_at'], name='stores_stor_created_a586c7_idx'),
        ),
    ]
