# Generated by Django 5.0.2 on 2025-06-24 22:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('users', '0004_rename_seller_homepage_products_seller_id_order_idx_seller_home_seller__3ed534_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('flat', 'Flat Discount')], max_length=15)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='users.sellerprofile')),
            ],
            options={
                'db_table': 'product_offers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'status'], name='product_off_product_9b606f_idx'), models.Index(fields=['seller', 'status'], name='product_off_seller__5adc4b_idx'), models.Index(fields=['start_date', 'end_date'], name='product_off_start_d_5ca00b_idx'), models.Index(fields=['status'], name='product_off_status_d102e6_idx')],
            },
        ),
    ]
